export default [
  [
    {caption: "tab", code: 9, id: "tab"},
    {caption: "q", code: 81, finger: "left-pinky"},
    {caption: "w", code: 87, finger: "left-ring"},
    {caption: "e", code: 69, finger: "left-middle"},
    {caption: "r", code: 82, finger: "left-index"},
    {caption: "t", code: 84, finger: "left-index"},
    {caption: "y", code: 89, finger: "right-index"},
    {caption: "u", code: 85, finger: "right-index"},
    {caption: "i", code: 73, finger: "right-middle"},
    {caption: "o", code: 79, finger: "right-ring"},
    {caption: "p", code: 80, finger: "right-pinky"},
    {caption: "[", code: 219, id: "square-bracket"},
    {caption: "]", code: 221, id: "square-bracket"},
    {caption: "\\", code: 220, id: "slash"}
  ],
  [
    {caption: "caps", code: 20, id: "caps"},
    {caption: "a", code: 65, finger: "left-pinky"},
    {caption: "s", code: 83, finger: "left-ring"},
    {caption: "d", code: 68, finger: "left-middle"},
    {caption: "f", code: 70, finger: "left-index"},
    {caption: "g", code: 71, finger: "left-index"},
    {caption: "h", code: 72, finger: "right-index"},
    {caption: "j", code: 74, finger: "right-index"},
    {caption: "k", code: 75, finger: "right-middle"},
    {caption: "l", code: 76, finger: "right-ring"},
    {caption: ":", code: 186, id: "colon"},
    {caption: "'", code: 222, id: "coma"},
    {caption: "return", code: 13, id: "enter"}
  ],
  [
    {caption: "shift", code: 16, id: "shiftleft"},
    {caption: "z", code: 90, finger: "left-pinky"},
    {caption: "x", code: 88, finger: "left-ring"},
    {caption: "c", code: 67, finger: "left-middle"},
    {caption: "v", code: 86, finger: "left-index"},
    {caption: "b", code: 66, finger: "left-index"},
    {caption: "n", code: 78, finger: "right-index"},
    {caption: "m", code: 77, finger: "right-index"},
    {caption: ",", code: 188, id: "coma"},
    {caption: ".", code: 190, id: "dot"},
    {caption: "/", code: 191, id: "slash"},
    {caption: "shift", code: 61, id: "shiftright"},
  ],
  [
    {caption: "fn", code: 0, id: "fn", key: 1},
    {caption: "control", code: 17, id: "control", key: 2},
    {caption: "option", code: 0, id: "optionleft", key: 3},
    {caption: "command", code: 0, id: "commandleft", key: 4},
    {caption: " ", className: "spacebar", code: 32, id: "spacebar", key: 5, finger: "left-thumb"},
    {caption: "command", code: 0, id: "commandright", key: 6},
    {caption: "option", code: 0, id: "optionright", key: 7}
  ]
]