export default [
  [
    {caption: "tab", code: 9, id: "tab"},
    {caption: "q", code: 81},
    {caption: "w", code: 87},
    {caption: "e", code: 69},
    {caption: "r", code: 82},
    {caption: "t", code: 84},
    {caption: "y", code: 89},
    {caption: "u", code: 85},
    {caption: "i", code: 73},
    {caption: "o", code: 79},
    {caption: "p", code: 80},
    {caption: "[", code: 219, id: "square-bracket"},
    {caption: "]", code: 221, id: "square-bracket"},
    {caption: "\\", code: 220, id: "slash"}
  ],
  [
    {caption: "caps", code: 20, id: "caps"},
    {caption: "a", code: 65},
    {caption: "s", code: 83},
    {caption: "d", code: 68},
    {caption: "f", code: 70},
    {caption: "g", code: 71},
    {caption: "h", code: 72},
    {caption: "j", code: 74},
    {caption: "k", code: 75},
    {caption: "l", code: 76},
    {caption: ":", code: 186},
    {caption: "'", code: 222},
    {caption: "return", code: 13, id: "enter"}
  ],
  [
    {caption: "shift", code: 16, id: "shiftleft"},
    {caption: "z", code: 90},
    {caption: "x", code: 88},
    {caption: "c", code: 67},
    {caption: "v", code: 86},
    {caption: "b", code: 66},
    {caption: "n", code: 78},
    {caption: "m", code: 77},
    {caption: ",", code: 188},
    {caption: ".", code: 190},
    {caption: "/", code: 191},
    {caption: "shift", code: 61, id: "shiftright"},
  ]
]