export default [
  [
    {caption: "tab", pressed: false, hightlighted: false, code: 9, id: "tab"},
    {caption: "q", pressed: false, hightlighted: false, code: 81},
    {caption: "w", pressed: false, hightlighted: false, code: 87},
    {caption: "e", pressed: false, hightlighted: false, code: 69},
    {caption: "r", pressed: false, hightlighted: false, code: 82},
    {caption: "t", pressed: false, hightlighted: false, code: 84},
    {caption: "y", pressed: false, hightlighted: false, code: 89},
    {caption: "u", pressed: false, hightlighted: false, code: 85},
    {caption: "i", pressed: false, hightlighted: false, code: 73},
    {caption: "o", pressed: false, hightlighted: false, code: 79},
    {caption: "p", pressed: false, hightlighted: false, code: 80},
    {caption: "[", pressed: false, hightlighted: false, code: 219, id: "square-bracket"},
    {caption: "]", pressed: false, hightlighted: false, code: 221, id: "square-bracket"},
    {caption: "\\", pressed: false, hightlighted: false, code: 220, id: "slash"}
  ],
  [
    {caption: "caps", pressed: false, hightlighted: false, code: 20, id: "caps"},
    {caption: "a", pressed: false, hightlighted: false, code: 65},
    {caption: "s", pressed: false, hightlighted: false, code: 83},
    {caption: "d", pressed: false, hightlighted: false, code: 68},
    {caption: "f", pressed: false, hightlighted: false, code: 70},
    {caption: "g", pressed: false, hightlighted: false, code: 71},
    {caption: "h", pressed: false, hightlighted: false, code: 72},
    {caption: "j", pressed: false, hightlighted: false, code: 74},
    {caption: "k", pressed: false, hightlighted: false, code: 75},
    {caption: "l", pressed: false, hightlighted: false, code: 76},
    {caption: ":", pressed: false, hightlighted: false, code: 186},
    {caption: "'", pressed: false, hightlighted: false, code: 222},
    {caption: "return", pressed: false, hightlighted: false, code: 13, id: "enter"}
  ],
  [
    {caption: "shift", pressed: false, hightlighted: false, code: 16, id: "shiftleft"},
    {caption: "z", pressed: false, hightlighted: false, code: 90},
    {caption: "x", pressed: false, hightlighted: false, code: 88},
    {caption: "c", pressed: false, hightlighted: false, code: 67},
    {caption: "v", pressed: false, hightlighted: false, code: 86},
    {caption: "b", pressed: false, hightlighted: false, code: 66},
    {caption: "n", pressed: false, hightlighted: false, code: 78},
    {caption: "m", pressed: false, hightlighted: false, code: 77},
    {caption: ",", pressed: false, hightlighted: false, code: 188},
    {caption: ".", pressed: false, hightlighted: false, code: 190},
    {caption: "/", pressed: false, hightlighted: false, code: 191},
    {caption: "shift", pressed: false, hightlighted: false, code: 61, id: "shiftright"},
  ]
]